### PR TITLE
JSAB2-87 Leaderboard additions

### PR DESCRIPTION
**Pull request by kyya**

### CODE REVIEW

**Review by GuJialu — APPROVED** [review]

**Review by HONGTAO-T — APPROVED** [review]

**Review by HanqingZ — APPROVED** [review]

**Review by evasimonyi — CHANGES_REQUESTED** [review]
on my iPhone (after yarn and every update) it says: 
`TouchableNativeFeedback is not supported on this platform!`
I could attach the screenshot only in JIRA, see the link below, please check!

https://jira.greenfox.academy/browse/JSAB2-87?focusedCommentId=11426&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-11426

also on Android (it looks great!), but the underlining of the active MenuItem is really short, and looks strange, can you check that too, please?

**Comment by kyya** [comment]
I have found it and I'm going to fix it today.

**Review by HanqingZ — APPROVED** [review]

**Review by HONGTAO-T — APPROVED** [review]

**Review by GuJialu — APPROVED** [review]

**Review by evasimonyi — APPROVED** [review]
👍 💯

**Pull request merged**
